regiony pvp:
  - wymiencie
  - tutaj
  - regiony na ktorych walacza
  - tylko gracze.

regiony dungeon:
  - wymiencie
  - tutaj
  - regiony na ktorych
  - walcza tez moby.
#Tutaj wpisz ile ma cooldown trwac.
cooldown: